### PR TITLE
chore(api): add link to component props in short text

### PR DESCRIPTION
**Pull request by simonssspirit**

### CODE REVIEW

**Comment by simonssspirit** [comment]
With this change, we are setting a direct link to the component props inside the component description. This is due to the feedback received from the users that they cannot find the properties after landing on the component page.

**Review by kirchoni — CHANGES_REQUESTED** [review]
IMO, trying to guess the slug, might lead to some unintentional wrong slugs. 
For example, the `GridToolbar` component does not have a props interface, but with this change a slug `api_grid_gridtoolbarprops` will be generated, even tho the interface is missing.

**Comment by simonssspirit** [comment]
Currently, this change can produce only issues in cases where we have a component that has no props Interface. We should discuss if there is a use case of having a public component that receives no properties, as in IMO if a component has no props it can be replaced with a renderer.
cc: @telerik/kendo-react-team  please share your thoughts

**Comment by eeasss** [comment]
I think that for the greater good we should go ahead. 

May be the code can be augmented in a way that no  slug is added in case of no properties interface? Do we have this info in the model?

**Comment by simonssspirit** [comment]
Unfortunately, I did not found this information, as the Component does not know if an interface will be added. We may be able to programmatically create this information by looping through all of the items and setting a flag, but IMO a "hack" like this could create more issues then simply ensuring that a component will have props or if it doesn't it will be a stateless functional component as recommended in the React documentation.

**Comment by Xizario** [comment]
But the `Toolbar` actually have the base props from ReactComponent.

**Comment by eeasss** [comment]
guys are we merging this one? Kiko is your request for change still valid?

**Comment by simonssspirit** [comment]
@eeasss We were waiting for the change inside the Grid props. The change is already made by @Xizario and I think that we are ready to merge. We agree that a component should always have Pops even is it is only the children prop.

**Review by kirchoni — APPROVED** [review]
We've changed the `Toolbar` component to have prop interface, as it it the _right_ way to expose props instead relying on react to apply the default ones.

**Pull request merged**
